export const BODY_LOAD_VIDEO = 'BODY_LOAD_VIDEO';
export const FETCH_STATUS_HISTORY = "FETCH_STATUS_HISTORY";
export const DATA_STATUS_HISTORY = "DATA_STATUS_HISTORY";
export const DATA_STATUS_HISTORY_CHILDREN = "DATA_STATUS_HISTORY_CHILDREN";
export const IS_SHOW_POPUP_HISTORY = "IS_SHOW_POPUP_HISTORY";
